name: CI/CD > PasswordManager Dev

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  publish-images:
    name: Connecting to server for deployment
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END

      - name: Run Deploy
        run: |
          ssh target "\
            export PATH=/root/.nvm/versions/node/v20.17.0/bin:\$PATH && \
            cd frontends/PasswordManager-Client/ && \
            git pull && \
            export PATH=\$PATH:/root/.npm/bin && \
            npm run build && \
            cp -r ./build/* /var/www/pm/html/ && \
            systemctl reload nginx"
